[build]
target = "thumbv7em-none-eabi"

[target.thumbv7em-none-eabi]
# `runner.sh` is created dynamically by build.rs based on the chosen chip ID
runner = ["sh", "-c", "${OUT_DIR}/runner.sh \"$@\"", "--"]

[profile.dev]
opt-level = "s"

[profile.release]
opt-level = 3
debug = 2
lto = "fat"
codegen-units = 1
panic = "abort"

[env]
